### PR TITLE
added endpoint users/teachers/{UserId}/get-all-documents

### PR DESCRIPTION
**Pull request by rezapps**
Created directory Teachers/GetDocuments
added endpoint users/teachers/{UserId}/get-all-documents
added DocumentBaseModel to LMS/Core/Models

### CODE REVIEW

**Review by suny-am — COMMENTED** [review]
Snyggt!

Du skulle kunna uppdatera `LMS.Data/Seeds/BaseSeeds.cs` med några test-dokument så att vi kan visa ut något när man anropar denna endpoint.

**Review by rezapps — COMMENTED** [review]
Added GenerateDocuments method to BaseSeed and merged development into feature/teacher-get-all-documents

**Review by suny-am — CHANGES_REQUESTED** [review]
It would be good to merge development into the branch to get all the latest updates (for example, the `DOTNET_ENVIRONMENT` variable is no longer used in Linux/Docker env; instead use `CONTAINER_ENV=true`

**Comment by rezapps** [comment]
development is merged into feature/teacher-get-documents, in  commit [1ab0395](https://github.com/Sunyam-Lexicon-2024/lms/pull/7/commits/1ab03958a9625cbe2c1e746e7bbbbc4ee8cb82fd)

**Pull request closed without merging**
